version: '2.10.2'

services:
  # Vue + Node.js
  web:
    container_name: web_eoffice
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: webeoffice:1.0
    volumes:
      - web_eoffice:/var/www
    ports:
      - "8012:80"
    networks:
      - app-network
  
  # PHP + Composer
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: appeoffice:1.0
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME=app 
      - SERVICE_TAGS=dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_PORT=5433
    working_dir: /var/www
    volumes:
      - app_eoffice:/var/www
      - ./backend/extern/conf.d/php-local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx
  server:
    image: nginx:alpine
    container_name: server_eoffice
    restart: unless-stopped
    tty: true
    ports:
      - "8090:80"
    volumes:
      - app_eoffice:/var/www
      - ./backend/extern/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network
  
  db:
    image: "postgres:bullseye"
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=eoffice
    networks:
      - app-network
    volumes:
      - db_eoffice:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  web_eoffice:
  app_eoffice:
  db_eoffice: